import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import darkTheme from "./dark-theme";
import customTheme from "./theme"
import { CssBaseline, ThemeProvider } from "@mui/material";
import { Container  } from "@mui/material";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <ThemeProvider theme={customTheme}>
            <CssBaseline/>
            <Container>{children}</Container>
          </ThemeProvider>
        </AppRouterCacheProvider>
        
        
      </body>
    </html>
  );
}
